name: Superlinear
favicon: null
layout_spectrum: 0.29148
typography_spectrum: 0.50393
title: 'Superlinear Limited, London, UK.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73105265-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fad961'
    - '#000000'
    - '#f66b1c'
    - '#806f32'
    - '#572500'
  brandStrength: 0.375
  lightness: 0.375
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
