name: Superlinear
favicon: null
layout_spectrum: 0.5248904374893755
typography_spectrum: 0.4421510922256857
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.34630057285539806
  lightness: 0.030614511808380485
  saturation: 0.41720660985447466
  rhythmicContrast: 0.6103174085728824
purpose: []
